/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jframekash;

import banco.TbUsuario;
import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.sistema.Sistema;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class TelaSO extends javax.swing.JFrame {
    
    Looca looca = new Looca();
    Sistema sistema = looca.getSistema();
    ImageIcon img = new ImageIcon("src/main/resources/logoWhite.png");
    TbUsuario usuario = new TbUsuario();
    
    /**
     * Creates new form TelaSO
     */
    public TelaSO() {
        initComponents();
        
        String permissao;        
        if (sistema.getPermissao() == false) {
            permissao = "Executando como usuário padrão";
        }else {
            permissao = "Executando como administrador";
        }
        
        lblSistema.setText(lblSistema.getText() + sistema.getSistemaOperacional());
        lblFabricante.setText(lblFabricante.getText() + sistema.getFabricante());
        lblArquitetura.setText(lblArquitetura.getText() + sistema.getArquitetura().toString() + "bits");
        lblInicializado.setText(lblInicializado.getText() + sistema.getInicializado().toString());
        lblPermissao.setText(lblPermissao.getText() + permissao);
        
        Double tempo = Double.valueOf(sistema.getTempoDeAtividade()).doubleValue()/ 60/60;
        Double tempoHoras = Math.round(tempo * 10.0) / 10.0;
        
        lblTempoAtivo.setText(lblTempoAtivo.getText() + tempoHoras.toString() + " horas");
        
        img.setImage(img.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 1));
        lblLogo.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalProcessos = new javax.swing.JLabel();
        lblTotalThreads = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCPU = new javax.swing.JButton();
        btnDisco = new javax.swing.JButton();
        btnMemo = new javax.swing.JButton();
        lblSistema = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblArquitetura = new javax.swing.JLabel();
        lblInicializado = new javax.swing.JLabel();
        lblPermissao = new javax.swing.JLabel();
        lblTempoAtivo = new javax.swing.JLabel();
        btnProcessos = new javax.swing.JButton();
        btnTemp = new javax.swing.JButton();

        lblTotalProcessos.setText("Total de Processos: ");

        lblTotalThreads.setText("Total de Threads: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 510));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoWhite.png"))); // NOI18N
        lblLogo.setAlignmentX(-18.0F);
        lblLogo.setAlignmentY(-200.0F);

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTitulo.setText("Sistema Operacional");

        btnCPU.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnCPU.setText("CPU");
        btnCPU.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        btnDisco.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnDisco.setText("Disco");
        btnDisco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscoActionPerformed(evt);
            }
        });

        btnMemo.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnMemo.setText("Memória");
        btnMemo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoActionPerformed(evt);
            }
        });

        lblSistema.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSistema.setText("Sistema operacional: ");

        lblFabricante.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblFabricante.setText("Fabricante: ");

        lblArquitetura.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblArquitetura.setText("Arquitetura: ");

        lblInicializado.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblInicializado.setText("Inicializado: ");

        lblPermissao.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblPermissao.setText("Permissão: ");

        lblTempoAtivo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblTempoAtivo.setText("Tempo de atividade: ");

        btnProcessos.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnProcessos.setText("Processos");
        btnProcessos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessosActionPerformed(evt);
            }
        });

        btnTemp.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnTemp.setText("Temperatura");
        btnTemp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCPU)
                    .addComponent(btnDisco)
                    .addComponent(btnMemo)
                    .addComponent(btnProcessos)
                    .addComponent(btnTemp))
                .addGap(240, 240, 240)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempoAtivo)
                    .addComponent(lblArquitetura)
                    .addComponent(lblInicializado)
                    .addComponent(lblFabricante)
                    .addComponent(lblSistema)
                    .addComponent(lblPermissao))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTitulo)))
                .addGap(37, 37, 37)
                .addComponent(lblSistema)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFabricante)
                        .addGap(18, 18, 18)
                        .addComponent(lblArquitetura)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicializado)
                        .addGap(18, 18, 18)
                        .addComponent(lblPermissao)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempoAtivo)
                        .addGap(33, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCPU)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisco)
                        .addGap(18, 18, 18)
                        .addComponent(btnMemo)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessos)
                        .addGap(18, 18, 18)
                        .addComponent(btnTemp)
                        .addGap(85, 85, 85))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
        TelaCPU in = new TelaCPU();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoActionPerformed
        TelaMemoria in = new TelaMemoria();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnMemoActionPerformed

    private void btnProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessosActionPerformed
        TelaProcessos in = new TelaProcessos();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnProcessosActionPerformed

    private void btnDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscoActionPerformed
        TelaDisco in = new TelaDisco();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnDiscoActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        TelaTemperatura in = new TelaTemperatura();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setResizable(false);
        this.dispose();    }//GEN-LAST:event_btnTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPU;
    private javax.swing.JButton btnDisco;
    private javax.swing.JButton btnMemo;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JButton btnTemp;
    private javax.swing.JLabel lblArquitetura;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblInicializado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPermissao;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JLabel lblTempoAtivo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalProcessos;
    private javax.swing.JLabel lblTotalThreads;
    // End of variables declaration//GEN-END:variables
}
